name: Dev Tests - Daxiongmao87
env:
  EXPANSION: classic
  GH_TOKEN: ${{ github.token }}
  BRANCH: dev-daxiongmao87
on:
  workflow_dispatch:
    inputs:
      mangos_commit:
        description: "Enter the mangos commit SHA (leave blank for automatic selection)"
        required: false
        default: ""
      playerbots_commit:
        description: "Enter the playerbots commit SHA (leave blank for automatic selection)"
        required: false
        default: ""
      db_commit:
        description: "Enter the db commit SHA (leave blank for automatic selection)"
        required: false
        default: ""
  workflow_run:
    workflows: ["ubuntu.yml", "build-release.yml"]
    types:
      - completed

permissions:
  contents: write

jobs:
  nightly_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0
          ref: ${{ env.BRANCH }}

      - name: Fetch mangos commit (if not provided)
        id: fetch_mangos_commit
        run: |
          if [ -z "${{ github.event.inputs.mangos_commit }}" ]; then
            MANGOS_COMMIT=$(curl -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/cmangos/mangos-$EXPANSION/actions/workflows/ubuntu.yml/runs?status=success | jq -r ".workflow_runs[0].head_sha")
          else
            MANGOS_COMMIT=${{ github.event.inputs.mangos_commit }}
          fi
          echo "::set-output name=mangos_commit::$MANGOS_COMMIT"
      - name: Fetch playerbots commit (if not provided)
        id: fetch_playerbots_commit
        run: |
          if [ -z "${{ github.event.inputs.playerbots_commit }}" ]; then
            PLAYERBOTS_COMMIT=$(curl -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/cmangos/playerbots/actions/workflows/cmangos-ubuntu-build.yml/runs?status=success | jq -r ".workflow_runs[0].head_sha")
          else
            PLAYERBOTS_COMMIT=${{ github.event.inputs.playerbots_commit }}
          fi
          echo "::set-output name=playerbots_commit::$PLAYERBOTS_COMMIT"

      - name: Fetch database commit (if not provided)
        id: fetch_db_commits
        run: |
          if [ -z "${{ github.event.inputs.db_commit }}" ]; then
            DB_COMMITS=$(curl -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/cmangos/$EXPANSION-db/actions/runs?status=success | jq -r ".workflow_runs[].head_sha")
            for COMMIT in $DB_COMMITS; do
              DB_COMMIT_DATE=$(curl -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/cmangos/$EXPANSION-db/commits/$COMMIT | jq -r ".commit.committer.date")
              MANGOS_COMMIT_DATE=$(curl -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/cmangos/mangos-$EXPANSION/commits/${{ steps.fetch_mangos_commit.outputs.mangos_commit }} | jq -r ".commit.committer.date")

              # Convert to UTC and compare
              DB_COMMIT_DATE_UTC=$(date -u -d "$DB_COMMIT_DATE" +%Y-%m-%dT%H:%M:%SZ)
              MANGOS_COMMIT_DATE_UTC=$(date -u -d "$MANGOS_COMMIT_DATE" +%Y-%m-%dT%H:%M:%SZ)

              if [[ "$DB_COMMIT_DATE_UTC" < "$MANGOS_COMMIT_DATE_UTC" ]] || [[ "$DB_COMMIT_DATE_UTC" == "$MANGOS_COMMIT_DATE_UTC" ]]; then
                echo "::set-output name=db_commit::$COMMIT"
                exit 0
              fi
            done
          else
            echo "::set-output name=db_commit::${{ github.event.inputs.db_commit }}"
          fi

      - name: Update .env.template and rename to .env
        run: |
          sed -i "s/WOW_EXPANSION=.*/WOW_EXPANSION=${EXPANSION}/" .env.template
          sed -i "s/MANGOS_COMMIT_SHA=.*/MANGOS_COMMIT_SHA=${{ steps.fetch_mangos_commit.outputs.mangos_commit }}/" .env.template
          sed -i "s/PLAYERBOTS_COMMIT_SHA=.*/PLAYERBOTS_COMMIT_SHA=${{ steps.fetch_playerbots_commit.outputs.playerbots_commit }}/" .env.template
          sed -i "s/DB_COMMIT_SHA=.*/DB_COMMIT_SHA=${{ steps.fetch_db_commits.outputs.db_commit }}/" .env.template
          cp .env.template .env

      - name: Build with Docker
        run: |
          docker compose build
