name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_run:
    workflows: ["ubuntu.yml", "build-release.yml"]
    types:
      - completed

jobs:
  fetch_commits:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        expansion: [classic, tbc, wotlk] # Add flexibility for different expansions

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Fetch mangosd commit
        id: fetch_mangosd_commit
        run: |
          MANGOSD_COMMIT=$(curl -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/cmangos/mangos-${{ matrix.expansion }}/actions/runs?status=success | jq -r ".workflow_runs[0].head_sha")
          echo "::set-output name=mangosd_commit::$MANGOSD_COMMIT"

      - name: Fetch database commits
        id: fetch_db_commits
        run: |
          DB_COMMITS=$(curl -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/cmangos/${{ matrix.expansion }}-db/actions/runs?status=success | jq -r ".workflow_runs[].head_sha")
          for COMMIT in $DB_COMMITS; do
            DB_COMMIT_DATE=$(curl -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/cmangos/${{ matrix.expansion }}-db/commits/$COMMIT | jq -r ".commit.committer.date")
            MANGOSD_COMMIT_DATE=$(curl -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/cmangos/mangos-${{ matrix.expansion }}/commits/${{ steps.fetch_mangosd_commit.outputs.mangosd_commit }} | jq -r ".commit.committer.date")
            
            # Convert to UTC and compare
            DB_COMMIT_DATE_UTC=$(date -u -d "$DB_COMMIT_DATE" +%Y-%m-%dT%H:%M:%SZ)
            MANGOSD_COMMIT_DATE_UTC=$(date -u -d "$MANGOSD_COMMIT_DATE" +%Y-%m-%dT%H:%M:%SZ)
      
            if [[ "$DB_COMMIT_DATE_UTC" < "$MANGOSD_COMMIT_DATE_UTC" ]] || [[ "$DB_COMMIT_DATE_UTC" == "$MANGOSD_COMMIT_DATE_UTC" ]]; then
              echo "::set-output name=db_commit::$COMMIT"
              exit 0
            fi
          done
      
          echo "No valid database commit found that is not newer than the mangosd commit."
          exit 1

  build_and_tag:
    needs: fetch_commits
    runs-on: ubuntu-latest
    strategy:
      matrix:
        expansion: [classic, tbc, wotlk] # Add flexibility for different expansions

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Update .env.template and rename to .env
        run: |
          sed -i "s/MANGOS_COMMIT_SHA=.*/MANGOS_COMMIT_SHA=${{ steps.fetch_mangosd_commit.outputs.mangosd_commit }}/" .env.template
          sed -i "s/DB_COMMIT_SHA=.*/DB_COMMIT_SHA=${{ steps.fetch_db_commits.outputs.db_commit }}/" .env.template
          cp .env.template .env
          cat .env

      - name: Build with Docker
        run: |
          ls -la
          docker compose build

      - name: Create nightly tag
        run: |
          DATE=$(date +'%Y-%m-%d')
          TAG_NAME="nightly-${{ matrix.expansion }}-${DATE}"
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Commit and push .env
        run: |
          git add .env
          git commit -m "Update .env with new commit SHAs for ${{ matrix.expansion }}"
          git push origin main

      - name: Notify via Slack
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "Nightly build failed for cmangos_wowbots_classic ${{ matrix.expansion }}."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
